### ISSUE TITLE
Limbo crashes on colab

### ISSUE THREAD

**Issue by franz101** [tursodatabase/limbo#494]
https://colab.research.google.com/drive/1llbFK082nh2JLDZ4Z-d0q-9j-bXtaCCE?usp=sharing

**Comment by jussisaurio** [comment]
```
VALUES (?, ?, ?)
```

SQL parameters are not implemented yet.

**Comment by jussisaurio** [comment]
~~I changed the name of the issue to reflect the cause of the crash and edited your OP~~

edit: reverted, seems i was wrong about the cause

**Comment by krishvishal** [comment]
I just looked at Colab notebook. It is crashing on `conn.commit()`. I think its because commit transaction is not implemented yet.

You can verify the crash by running it line by line [here](https://colab.research.google.com/drive/1nWBOqsCLI-axpPjGjOQTEz643QIPMZnx?usp=sharing).

**Comment by jussisaurio** [comment]
ok seems i was too quick to jump to conclusions, just assumed

**Comment by franz101** [comment]
ah yeah, I was curious about a simple POC

**Comment by LtdJorge** [comment]
Full log:

|Timestamp|Level|Message|
|---|---|---|
|Dec 17, 2024, 9:07:03 PM|WARNING|WARNING:root:kernel b568fa9e-533e-4316-92a1-78ddd94b713d restarted|
|Dec 17, 2024, 9:07:03 PM|INFO|KernelRestarter: restarting kernel \(1/5\), keep random ports|
|Dec 17, 2024, 9:07:02 PM|WARNING|note: run with `RUST\_BACKTRACE=1` environment variable to display a backtrace|
|Dec 17, 2024, 9:07:02 PM|WARNING|not yet implemented|
|Dec 17, 2024, 9:07:02 PM|WARNING|thread '\<unnamed\>' panicked at bindings/python/src/lib\.rs:226:9:|
|Dec 17, 2024, 9:06:36 PM|INFO|Kernel started: b568fa9e-533e-4316-92a1-78ddd94b713d, name: python3|
|Dec 17, 2024, 9:04:42 PM|INFO|Use Control-C to stop this server and shut down all kernels \(twice to skip confirmation\)\.|
|Dec 17, 2024, 9:04:42 PM|INFO|Use Control-C to stop this server and shut down all kernels \(twice to skip confirmation\)\.|
|Dec 17, 2024, 9:04:42 PM|INFO|http://172\.28\.0\.12:9000/|
|Dec 17, 2024, 9:04:42 PM|INFO|Jupyter Notebook 6\.5\.5 is running at:|
|Dec 17, 2024, 9:04:42 PM|INFO|http://172\.28\.0\.2:9000/|
|Dec 17, 2024, 9:04:42 PM|INFO|Serving notebooks from local directory: /|
|Dec 17, 2024, 9:04:42 PM|INFO|Jupyter Notebook 6\.5\.5 is running at:|
|Dec 17, 2024, 9:04:42 PM|INFO|Serving notebooks from local directory: /|
|Dec 17, 2024, 9:04:31 PM|INFO|Loading IPython parallel extension|
|Dec 17, 2024, 9:04:31 PM|INFO|Loading IPython parallel extension|
|Dec 17, 2024, 9:04:31 PM|INFO|google\.colab serverextension initialized\.|
|Dec 17, 2024, 9:04:31 PM|INFO|Authentication of /metrics is OFF, since other authentication is disabled\.|
|Dec 17, 2024, 9:04:31 PM|INFO|Writing notebook server cookie secret to /root/\.local/share/jupyter/runtime/notebook\_cookie\_secret|
|Dec 17, 2024, 9:04:31 PM|WARNING|    	/root/\.jupyter/jupyter\_notebook\_config\.json|
|Dec 17, 2024, 9:04:31 PM|WARNING|    	/root/\.local/etc/jupyter/jupyter\_notebook\_config\.json|
|Dec 17, 2024, 9:04:31 PM|INFO|google\.colab serverextension initialized\.|
|Dec 17, 2024, 9:04:31 PM|WARNING|    	/usr/etc/jupyter/jupyter\_notebook\_config\.json|
|Dec 17, 2024, 9:04:31 PM|WARNING|    	/usr/local/etc/jupyter/jupyter\_notebook\_config\.json|
|Dec 17, 2024, 9:04:31 PM|WARNING|    	/usr/local/etc/jupyter/jupyter\_notebook\_config\.d/panel-client-jupyter\.json|
|Dec 17, 2024, 9:04:31 PM|WARNING|    	/usr/local/etc/jupyter/jupyter\_notebook\_config\.d/ipyparallel\.json|
|Dec 17, 2024, 9:04:31 PM|WARNING|    	/etc/jupyter/jupyter\_notebook\_config\.json|
|Dec 17, 2024, 9:04:30 PM|INFO|Authentication of /metrics is OFF, since other authentication is disabled\.|
|Dec 17, 2024, 9:04:30 PM|INFO|Writing notebook server cookie secret to /root/\.local/share/jupyter/runtime/notebook\_cookie\_secret|
|Dec 17, 2024, 9:04:30 PM|WARNING|    	/root/\.jupyter/jupyter\_notebook\_config\.json|
|Dec 17, 2024, 9:04:30 PM|WARNING|    	/root/\.local/etc/jupyter/jupyter\_notebook\_config\.json|
|Dec 17, 2024, 9:04:30 PM|WARNING|    	/usr/etc/jupyter/jupyter\_notebook\_config\.json|
|Dec 17, 2024, 9:04:30 PM|WARNING|    	/usr/local/etc/jupyter/jupyter\_notebook\_config\.json|
|Dec 17, 2024, 9:04:30 PM|WARNING|    	/usr/local/etc/jupyter/jupyter\_notebook\_config\.d/panel-client-jupyter\.json|
|Dec 17, 2024, 9:04:30 PM|WARNING|    	/usr/local/etc/jupyter/jupyter\_notebook\_config\.d/ipyparallel\.json|
|Dec 17, 2024, 9:04:30 PM|WARNING|    	/etc/jupyter/jupyter\_notebook\_config\.json|
|Dec 17, 2024, 9:04:29 PM|WARNING|\[D 20:04:29\.806 NotebookApp\] Loaded config file: /root/\.jupyter/jupyter\_notebook\_config\.py|
|Dec 17, 2024, 9:04:29 PM|WARNING|\[D 20:04:29\.804 NotebookApp\] Looking for jupyter\_notebook\_config in /root/\.jupyter|
|Dec 17, 2024, 9:04:29 PM|WARNING|\[D 20:04:29\.804 NotebookApp\] Looking for jupyter\_notebook\_config in /root/\.local/etc/jupyter|
|Dec 17, 2024, 9:04:29 PM|WARNING|\[D 20:04:29\.803 NotebookApp\] Looking for jupyter\_notebook\_config in /usr/etc/jupyter|
|Dec 17, 2024, 9:04:29 PM|WARNING|\[D 20:04:29\.802 NotebookApp\] Loaded config file: /usr/local/etc/jupyter/jupyter\_notebook\_config\.json|
|Dec 17, 2024, 9:04:29 PM|WARNING|\[D 20:04:29\.801 NotebookApp\] Looking for jupyter\_notebook\_config in /usr/local/etc/jupyter|
|Dec 17, 2024, 9:04:29 PM|WARNING|\[D 20:04:29\.800 NotebookApp\] Loaded config file: /etc/jupyter/jupyter\_notebook\_config\.py|
|Dec 17, 2024, 9:04:29 PM|WARNING|\[D 20:04:29\.799 NotebookApp\] Looking for jupyter\_notebook\_config in /etc/jupyter|
|Dec 17, 2024, 9:04:29 PM|WARNING|\[D 20:04:29\.798 NotebookApp\] Looking for jupyter\_config in /root/\.jupyter|
|Dec 17, 2024, 9:04:29 PM|WARNING|\[D 20:04:29\.798 NotebookApp\] Looking for jupyter\_config in /root/\.local/etc/jupyter|
|Dec 17, 2024, 9:04:29 PM|WARNING|\[D 20:04:29\.798 NotebookApp\] Looking for jupyter\_config in /usr/etc/jupyter|
|Dec 17, 2024, 9:04:29 PM|WARNING|\[D 20:04:29\.797 NotebookApp\] Looking for jupyter\_config in /usr/local/etc/jupyter|
|Dec 17, 2024, 9:04:29 PM|WARNING|\[D 20:04:29\.797 NotebookApp\] Looking for jupyter\_config in /etc/jupyter|
|Dec 17, 2024, 9:04:29 PM|WARNING|\[D 20:04:29\.796 NotebookApp\] Searching \['/root/\.jupyter', '/root/\.local/etc/jupyter', '/usr/etc/jupyter', '/usr/local/etc/jupyter', '/etc/jupyter'\] for config files|
|Dec 17, 2024, 9:04:29 PM|WARNING|\[D 20:04:29\.772 NotebookApp\] Loaded config file: /root/\.jupyter/jupyter\_notebook\_config\.py|
|Dec 17, 2024, 9:04:29 PM|WARNING|\[D 20:04:29\.765 NotebookApp\] Looking for jupyter\_notebook\_config in /root/\.jupyter|
|Dec 17, 2024, 9:04:29 PM|WARNING|\[D 20:04:29\.764 NotebookApp\] Looking for jupyter\_notebook\_config in /root/\.local/etc/jupyter|
|Dec 17, 2024, 9:04:29 PM|WARNING|\[D 20:04:29\.764 NotebookApp\] Looking for jupyter\_notebook\_config in /usr/etc/jupyter|
|Dec 17, 2024, 9:04:29 PM|WARNING|\[D 20:04:29\.763 NotebookApp\] Loaded config file: /usr/local/etc/jupyter/jupyter\_notebook\_config\.json|
|Dec 17, 2024, 9:04:29 PM|WARNING|\[D 20:04:29\.760 NotebookApp\] Looking for jupyter\_notebook\_config in /usr/local/etc/jupyter|
|Dec 17, 2024, 9:04:29 PM|WARNING|\[D 20:04:29\.760 NotebookApp\] Loaded config file: /etc/jupyter/jupyter\_notebook\_config\.py|
|Dec 17, 2024, 9:04:29 PM|WARNING|\[D 20:04:29\.757 NotebookApp\] Looking for jupyter\_notebook\_config in /etc/jupyter|
|Dec 17, 2024, 9:04:29 PM|WARNING|\[D 20:04:29\.755 NotebookApp\] Looking for jupyter\_config in /root/\.jupyter|
|Dec 17, 2024, 9:04:29 PM|WARNING|\[D 20:04:29\.755 NotebookApp\] Looking for jupyter\_config in /root/\.local/etc/jupyter|
|Dec 17, 2024, 9:04:29 PM|WARNING|\[D 20:04:29\.755 NotebookApp\] Looking for jupyter\_config in /usr/etc/jupyter|
|Dec 17, 2024, 9:04:29 PM|WARNING|\[D 20:04:29\.749 NotebookApp\] Looking for jupyter\_config in /usr/local/etc/jupyter|
|Dec 17, 2024, 9:04:29 PM|WARNING|\[D 20:04:29\.745 NotebookApp\] Looking for jupyter\_config in /etc/jupyter|
|Dec 17, 2024, 9:04:29 PM|WARNING|\[D 20:04:29\.736 NotebookApp\] Searching \['/root/\.jupyter', '/root/\.local/etc/jupyter', '/usr/etc/jupyter', '/usr/local/etc/jupyter', '/etc/jupyter'\] for config files|


Seems to me like the same issue in #502

**Comment by LtdJorge** [comment]
@krishvishal was right, the panic is because it hits `todo!()` in commit() for the Python bindings, disregard my previous comment.

**Comment by amuldotexe** [comment]
So perhaps the main task here is to gracefully handle this error & return a NotImplemented Error

Is that correct?

**Comment by LtdJorge** [comment]
> So perhaps the main task here is to gracefully handle this error & return a NotImplemented Error
> 
> Is that correct?

Commit is not implemented on the Rust side either. I think it's best to wait for that.

**Comment by franz101** [comment]
Ok, we can close this one and create a new one / link commit

**Comment by franz101** [comment]
with the commit commented out still crashing. or the insert / select be executed differently?
source
https://colab.research.google.com/drive/1llbFK082nh2JLDZ4Z-d0q-9j-bXtaCCE?usp=sharing

**Comment by penberg** [comment]
@franz101 We have `BEGIN IMMEDIATE` and `COMMIT` now, but I suspect we might need #1001 for this to work.

**Comment by penberg** [comment]
Blocked by https://github.com/tursodatabase/limbo/issues/1146

**Comment by penberg** [comment]
@diegoreis42 This is working now, right?

**Comment by franz101** [comment]
@penberg its working if you see the updated [notebook](https://colab.research.google.com/drive/1llbFK082nh2JLDZ4Z-d0q-9j-bXtaCCE?usp=sharing#scrollTo=y8fi9_J7YK2L) without commit.

it won't work currently with bounding variables correct?

 ```cur.execute("INSERT INTO users (username, email, role) VALUES (?, ?, ?)", (username, email, role))

OperationalError: Step error: Unbound(1)```

but 

```cur.execute("INSERT INTO users (username, email, role) VALUES (?, ?, ?)", ('username', 'email', 'role'))``` works

**Comment by el-yawd** [comment]
Hey @franz101 please try again with the new `0.0.18rc3` version. It should be working although it returns...

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/dist-packages/google/colab/_variable_inspector.py", line 27, in run
RuntimeError: _limbo::Connection is unsendable, but is being dropped on another thread

(1, 'alice', '[alice@example.com](mailto:alice@example.com)', 'admin', None) <--- Note the correct result

Traceback (most recent call last):
  File "/usr/local/lib/python3.11/dist-packages/google/colab/_variable_inspector.py", line 27, in run
RuntimeError: _limbo::Cursor is unsendable, but is being dropped on another thread
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/dist-packages/google/colab/_variable_inspector.py", line 27, in run
RuntimeError: _limbo::Cursor is unsendable, but is being dropped on another thread
```

... if you run multiple times, I'll open an issue to address this. Btw, we support bounding variables now, so:

```python
    cur.execute(
   f"""
    INSERT INTO users (username, email, role)
    VALUES (?, ?, ?)
    """,
    (username,  email,  role)
)
``` 

should works fine :)

**Comment by franz101** [comment]
Try running the linked notebook it comes with --pre. Looking promising but still throwing unbound

**Comment by el-yawd** [comment]
I noticed that colab makes some sort of caching of the dependencies, can you check if you're using the `0.0.18rc3` version?

![Image](https://github.com/user-attachments/assets/a16b2c65-5a6f-48a1-9352-ae1073d8ae27)

![Image](https://github.com/user-attachments/assets/8fcc5b3f-b87f-4c61-9dcf-bf6e867dbad9)
